"""
APEX server-side UNIVERSE FACTORY  (V4.6.73)
─────────────────────────────────────────────────────────────────
Generates a set of THEMED public universes on the Oracle server, NOT tied to
any user account. Bots (created in Make Bot) reference one of these by name, or
ship their own custom universe. Regenerated weekly (Monday at the US market
open) by the auto-scheduler.

Each universe is written in the SAME format the Universe tab uses:
    TICKER    # score=NN.N | <one-line reason>
so the desktop can read/display them like any other universe.

Themes:
    long_term     — durable momentum, lower volatility (buy-and-hold)
    short         — weakest momentum (short candidates)
    short_term    — most active / high churn (intraday & swing)
    speculative   — highest volatility (high risk / high reward)
    crypto        — major coins
    options       — liquid, high-volatility optionable names

Scoring uses 3-month daily bars from yfinance (free, no account). Best-effort:
a ticker that can't be priced is skipped; a theme with no data keeps its
previous file.
"""

from __future__ import annotations

import os
from datetime import datetime, timezone
from pathlib import Path

# Central, account-agnostic location for the public universes.
UNIVERSE_DIR = Path(os.environ.get("APEX_PUBLIC_UNIVERSE_DIR",
                                   "/opt/apex_data/universes"))

# Curated liquid base — scored each run; themes pick from it. Kept broad but
# bounded so one yfinance batch covers it quickly.
_BASE_STOCKS = [
    "AAPL", "MSFT", "NVDA", "GOOGL", "AMZN", "META", "AVGO", "TSLA", "AMD",
    "NFLX", "CRM", "ADBE", "ORCL", "QCOM", "MU", "INTC", "ARM", "DELL", "SMCI",
    "PLTR", "SNOW", "CRWD", "PANW", "NOW", "UBER", "ABNB", "SHOP", "SQ", "PYPL",
    "COIN", "HOOD", "MARA", "RIOT", "APP", "DDOG", "NET", "MDB", "ZS", "KLAC",
    "LRCX", "ASML", "TSM", "MRVL", "ON", "WDC", "STX", "JPM", "BAC", "GS", "MS",
    "V", "MA", "AXP", "BRK-B", "UNH", "LLY", "JNJ", "PFE", "MRK", "ABBV", "XOM",
    "CVX", "COP", "WMT", "COST", "HD", "NKE", "MCD", "SBUX", "DIS", "BA", "CAT",
    "GE", "F", "GM", "RIVN", "LCID", "NIO", "SOFI", "AFRM", "DKNG", "RBLX",
    "U", "PINS", "SNAP", "ROKU", "CVNA", "GME", "AMC", "SPY", "QQQ", "IWM",
]
_BASE_CRYPTO = [
    "BTC-USD", "ETH-USD", "SOL-USD", "XRP-USD", "ADA-USD", "AVAX-USD",
    "DOGE-USD", "LINK-USD", "DOT-USD", "MATIC-USD", "LTC-USD", "BCH-USD",
]

_PER_THEME = 35   # tickers emitted per stock theme


def _metrics(tickers: list) -> dict:
    """3-month momentum % + annualised volatility % + last price per ticker."""
    try:
        import yfinance as yf
        import numpy as np
    except Exception as e:
        print(f"[universe-factory] yfinance/numpy missing: {e}", flush=True)
        return {}
    out: dict = {}
    try:
        data = yf.download(tickers, period="3mo", interval="1d",
                           progress=False, group_by="ticker", threads=True)
    except Exception as e:
        print(f"[universe-factory] download failed: {e}", flush=True)
        return {}
    multi = len(tickers) > 1
    for t in tickers:
        try:
            close = (data[t]["Close"].dropna() if multi
                     else data["Close"].dropna())
            if len(close) < 20:
                continue
            mom = float(close.iloc[-1] / close.iloc[0] - 1.0) * 100.0
            rets = close.pct_change().dropna()
            vol = float(rets.std() * (252 ** 0.5) * 100.0)
            out[t] = {"mom": mom, "vol": vol, "price": float(close.iloc[-1])}
        except Exception:
            continue
    return out


def _emit(theme: str, ranked: list, blurb: str) -> int:
    """Write one themed universe file (TICKER  # score=.. | reason)."""
    try:
        UNIVERSE_DIR.mkdir(parents=True, exist_ok=True)
        now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        lines = [
            f"# APEX PUBLIC UNIVERSE — {theme}\n",
            f"# {blurb}\n",
            f"# Generated by universe_factory: {now}\n",
            f"# Total: {len(ranked)} tickers\n#\n",
        ]
        for t, score, reason in ranked:
            lines.append(f"{t:<10}  # score={score:.1f} | {reason}\n")
        (UNIVERSE_DIR / f"{theme}.txt").write_text("".join(lines),
                                                   encoding="utf-8")
        print(f"[universe-factory] wrote {theme}: {len(ranked)} tickers",
              flush=True)
        return len(ranked)
    except Exception as e:
        print(f"[universe-factory] emit {theme} failed: {e}", flush=True)
        return 0


def generate_all() -> dict:
    """Regenerate every themed public universe. Returns {theme: count}."""
    counts: dict = {}
    m = _metrics(_BASE_STOCKS)
    if m:
        def rank(scorer, reason_fn, n=_PER_THEME):
            scored = [(t, scorer(v), reason_fn(v)) for t, v in m.items()]
            scored.sort(key=lambda x: x[1], reverse=True)
            return scored[:n]

        counts["long_term"] = _emit(
            "long_term",
            rank(lambda v: v["mom"] - 0.30 * v["vol"],
                 lambda v: f"3mo {v['mom']:+.0f}%, vol {v['vol']:.0f}%"),
            "Durable momentum, volatility-penalised — buy & hold.")
        counts["short"] = _emit(
            "short",
            rank(lambda v: -v["mom"] - 0.10 * v["vol"],
                 lambda v: f"3mo {v['mom']:+.0f}%, vol {v['vol']:.0f}%"),
            "Weakest momentum — short candidates.")
        counts["short_term"] = _emit(
            "short_term",
            rank(lambda v: v["vol"] + abs(v["mom"]),
                 lambda v: f"vol {v['vol']:.0f}%, 3mo {v['mom']:+.0f}%"),
            "Most active / high churn — intraday & swing.")
        counts["speculative"] = _emit(
            "speculative",
            rank(lambda v: v["vol"],
                 lambda v: f"vol {v['vol']:.0f}%, 3mo {v['mom']:+.0f}%"),
            "Highest volatility — high risk / high reward.")
        counts["options"] = _emit(
            "options",
            rank(lambda v: v["vol"] if v["price"] > 15 else -1,
                 lambda v: f"vol {v['vol']:.0f}%, ${v['price']:.0f}"),
            "Liquid, high-volatility optionable names.")
    mc = _metrics(_BASE_CRYPTO)
    if mc:
        scored = [(t, v["mom"], f"3mo {v['mom']:+.0f}%, vol {v['vol']:.0f}%")
                  for t, v in mc.items()]
        scored.sort(key=lambda x: x[1], reverse=True)
        counts["crypto"] = _emit("crypto", scored,
                                 "Major coins by 3-month momentum.")
    return counts


def list_universes() -> list:
    """[{name, total, updated, header}] for every public universe file."""
    out = []
    if not UNIVERSE_DIR.exists():
        return out
    for p in sorted(UNIVERSE_DIR.glob("*.txt")):
        try:
            txt = p.read_text(encoding="utf-8")
            tickers = [ln.split("#")[0].strip()
                       for ln in txt.splitlines()
                       if ln.strip() and not ln.startswith("#")]
            hdr = next((ln[1:].strip() for ln in txt.splitlines()[1:2]), "")
            out.append({"name": p.stem, "total": len(tickers),
                        "blurb": hdr})
        except Exception:
            continue
    return out


def read_universe(name: str) -> str | None:
    p = UNIVERSE_DIR / f"{name}.txt"
    if not p.exists():
        return None
    try:
        return p.read_text(encoding="utf-8")
    except Exception:
        return None
