"""
APEX · build-time version embedder  (v3.1.7+)
─────────────────────────────────────────────────────────────────────
Writes the version from version.json into THREE places so the runtime
truly cannot end up reporting "1.0.0":

  1. apex_version.py   — top-level module (NO package, NO relative import)
                         core/updater.py does `import apex_version`
  2. core/_version.py  — same constant, kept for backward compat
  3. installer.iss     — replaces the MyAppVersion #define so the Inno
                         wizard shows the real version too

Called from build.bat BEFORE PyInstaller + ISCC. Idempotent.
"""

import json
import re
from pathlib import Path

ROOT = Path(__file__).parent.parent
VER_JSON  = ROOT / "version.json"
INSTALLER = ROOT / "installer.iss"

OUT_TOP   = ROOT / "apex_version.py"
OUT_CORE  = ROOT / "core" / "_version.py"

TEMPLATE  = '"""Generated by tools/embed_version.py — do NOT edit by hand."""\nVERSION = "{}"\n'

def main():
    version = json.loads(VER_JSON.read_text(encoding="utf-8")).get("version", "0.0.0")
    OUT_TOP.write_text(TEMPLATE.format(version), encoding="utf-8")
    OUT_CORE.write_text(TEMPLATE.format(version), encoding="utf-8")
    # Patch installer.iss
    if INSTALLER.exists():
        src = INSTALLER.read_text(encoding="utf-8")
        new = re.sub(
            r'(#define\s+MyAppVersion\s+")[^"]+(")',
            r'\g<1>' + version + r'\g<2>',
            src, count=1,
        )
        if new != src:
            INSTALLER.write_text(new, encoding="utf-8")
            print(f"[embed_version] installer.iss MyAppVersion -> {version}")
    print(f"[embed_version] {OUT_TOP.name} + {OUT_CORE.name} -> {version}")

    # V4.6.5 — nuke stale dist/APEX/. PyInstaller's --clean wipes its
    # *build cache* but leaves dist/ intact, so an unchanged
    # version.json gets bundled into every "fresh" build. Every
    # release v4.6.1 → v4.6.4 shipped with the v4.6.0 version.json
    # because of this. Wiping the output folder forces PyInstaller
    # to regenerate it from current source on the next build.
    #
    # V4.6.11 — also nuke build/APEX. If a previous PyInstaller run
    # was killed mid-build, build/APEX/APEX.exe stays locked by the
    # OS file cache for a while; PyInstaller's --clean then silently
    # falls back to STALE cached .pyc files for individual modules.
    # This is the root cause of the v4.6.10 "_populate_script_combo
    # not found" crash — the user got fresh version.json but old
    # universe.py inside the PYZ. Nuking build/ too prevents that.
    import shutil
    for sub in ("dist/APEX", "build/APEX"):
        p = ROOT / sub
        if p.exists():
            shutil.rmtree(p, ignore_errors=True)
            # If rmtree couldn't kill it (file lock), at least
            # detect that and warn loudly.
            if p.exists():
                print(f"[embed_version] WARNING: could not delete {p} — "
                      f"PyInstaller may reuse stale bytecode. Close any "
                      f"running APEX.exe and re-run.")
            else:
                print(f"[embed_version] nuked stale {sub}/")


def validate_dist_or_exit():
    """V4.6.23 — call this AFTER PyInstaller, BEFORE ISCC. Refuses to
    proceed if dist is incomplete. The v4.6.22 ship-failure was a
    PyInstaller crash that left a half-baked dist; ISCC happily
    packaged it into a 29 MB broken installer. This check stops that
    failure mode by refusing to compile if dist looks wrong."""
    must_exist = [
        ("dist/APEX/APEX.exe",                 10 * 1024 * 1024),
        ("dist/APEX/_internal/version.json",   100),
        ("dist/APEX/_internal/base_library.zip", 1 * 1024 * 1024),
    ]
    failed = []
    for rel, min_size in must_exist:
        p = ROOT / rel
        if not p.exists():
            failed.append(f"missing: {rel}")
            continue
        size = p.stat().st_size
        if size < min_size:
            failed.append(f"too small: {rel}  ({size} < {min_size})")
    if failed:
        print("[embed_version] DIST VALIDATION FAILED:")
        for f in failed:
            print(f"  - {f}")
        print("[embed_version] refusing to compile a broken installer.")
        import sys as _s
        _s.exit(2)
    # Also verify version.json matches what we just embedded
    import json as _j
    on_disk = _j.loads((ROOT / "dist/APEX/_internal/version.json")
                       .read_text(encoding="utf-8")).get("version", "")
    if on_disk != version:
        print(f"[embed_version] DIST VERSION MISMATCH: "
              f"expected {version}, dist has {on_disk}")
        import sys as _s
        _s.exit(2)
    print(f"[embed_version] dist validated — v{version}, "
          f"APEX.exe="
          f"{(ROOT / 'dist/APEX/APEX.exe').stat().st_size // 1024 // 1024} MB")


if __name__ == "__main__":
    import sys
    # When called with --validate-dist, do the post-PyInstaller check
    # instead of the pre-build embed.
    if len(sys.argv) > 1 and sys.argv[1] == "--validate-dist":
        # Read the version from version.json directly so we can call
        # validate_dist_or_exit() without re-running embed_version
        version = json.loads(VER_JSON.read_text(encoding="utf-8")).get(
            "version", "0.0.0")
        validate_dist_or_exit()
    else:
        main()
